service: serverless-contact-service

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
  apiKeys:
    - contack-key      
  environment:
    EMAIL_SENDER: 'falanga.fra@gmail.com'
    EMAIL_RECEIVER: 'falanga.fra@gmail.com'
    EMAIL_OBJECT: 'Referral Form'

package:
  include:
    - src/**
  exclude:
    - tmp/**
    - .git/*    
    - node_modules/**
    - '!node_modules/email-validator/**'
    - .coverage/**
    - tests/**
    - .jsconfig
    - .travis.yml    

functions:
  contact:
    handler: src/email.email
    events:
    - http:
        path: contact
        method: post
        cors: true
        private: true
        response:
          statusCodes:
            201:
              pattern: '' # Default response method


plugins:
  - serverless-offline